services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4321:3000'
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - app-data:/app/data
volumes:
  app-data:
